version: "3"

vars:
  CONFIG_PATH: "{{.HOME}}/.proglog/"

tasks:
  init:
    cmds:
      - mkdir -p {{.CONFIG_PATH}}
  gencert:
    cmds:
      - |
        cfssl gencert \
          -initca test/ca-csr.json | cfssljson -bare ca
      # - |
      #   cfssl gencert \
      #     -ca=ca.pem \
      #     -ca-key=ca-key.pem \
      #     -config=test/ca-config.json \
      #     -profile=server \
      #     test/server-csr.json | cfssljson -bare server
      - |
        cfssl gencert \
          -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=test/ca-config.json \
          -profile=client \
          test/client-csr.json | cfssljson -bare client
      - mv *.pem *.csr {{.CONFIG_PATH}}
  compile:
    cmds:
      - |
        protoc api/v1/*.proto \
          --go_out=. \
          --go-grpc_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_opt=paths=source_relative \
          --proto_path=.
  test:
    cmds:
      - go test -race ./...
