version: "3"

vars:
  CONFIG_PATH: "{{.HOME}}/.proglog/"

tasks:
  init:
    cmds:
      - mkdir -p {{.CONFIG_PATH}}
  gencert:
    cmds:
      - |
        cfssl gencert \
          -initca test/ca-csr.json | cfssljson -bare ca
      - |
        cfssl gencert \
          -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=test/ca-config.json \
          -profile=server \
          test/server-csr.json | cfssljson -bare server
      - |
        cfssl gencert \
          -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=test/ca-config.json \
          -profile=client \
          -cn="root" \
          test/client-csr.json | cfssljson -bare root-client
      - |
        cfssl gencert \
          -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=test/ca-config.json \
          -profile=client \
          -cn="nobody" \
          test/client-csr.json | cfssljson -bare nobody-client
      - mv *.pem *.csr {{.CONFIG_PATH}}
  compile:
    cmds:
      - |
        protoc api/v1/*.proto \
          --go_out=. \
          --go-grpc_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_opt=paths=source_relative \
          --proto_path=.
  copy-config:
    cmds:
      - cp test/model.conf {{.CONFIG_PATH}}/model.conf
      - cp test/policy.csv {{.CONFIG_PATH}}/policy.csv
    # 対応するファイルが存在しない場合のみコマンドを実行
    status:
      - test -f {{.CONFIG_PATH}}/model.conf
      - test -f {{.CONFIG_PATH}}/policy.csv

  # go test を実行するメインのタスク
  test:
    # 'copy-config' タスクを先に実行する
    deps: [copy-config]
    cmds:
      - go test -race ./...
